# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"

title                    : "Agnes Wang"
title_separator          : "-"
name                     : &name "Agnes Wang"
description              : &description "Computer Science Portfolio"

url                      : "https://agneswang42.github.io"
baseurl                  : ""
repository               : "agneswang42/agneswang42.github.io"

# Site Author
author:
  # Biographic information
  name             : "Agnes Wang"
  avatar           :
  bio              : "Computer Science Student"
  location         : "United States"
  education        : "Rose-Hulman Institute of Technology"
  employer         :
  email            : ""
  uri              :

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "agneswang42"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
